apiVersion: v1
kind: Secret
metadata:
  name: commafeed-db
  namespace: commafeed
type: Opaque
stringData:
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres-cluster-rw.postgres.svc.cluster.local:5432/commafeed"
  QUARKUS_DATASOURCE_USERNAME: "commafeed_user"
  QUARKUS_DATASOURCE_PASSWORD: "7CooN*5sDS4&yJ7@"
