apiVersion: v1
kind: Pod
metadata:
  name: debug-postgres-pvc
  namespace: postgres
spec:
  securityContext:
    runAsUser: 26
    runAsGroup: 26
  containers:
    - name: debug
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: postgres-cluster-1
