apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-configmap
data:
  PORT: "9000"
  SMTP_HOST: "smtp.mail.me.com"
  SMTP_PORT: "587"
  SMTP_FROM_NAME: "Kevin"
  SMTP_AUTH_STRATEGY: "TLS"
  SMTP_FROM_EMAIL: "kevink8s@icloud.com"
  SMTP_USER: "kevinmorrisone@icloud.com"
  SMTP_PASSWORD: "wujp-krqr-vbpy-dnit"
  BASE_URL: "http://mealie.kevin-morris.net"
