apiVersion: v1
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:3vzoJP8UeiT8Ze48pWVG1i+gA2Yvdb/O/SQQjFcKBFUSvPMH,iv:ePQWxvL6H3BNl7+HDtbuxIjAbHnl5mZBrABQ/1ygS7o=,tag:OgXIjmMO5/QyLoOwwis0wg==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:dOIrsN8SmVc=,iv:X533wS8n9y7KHzoHPqwhmpEt5mNHxOz7x+0czvW8ogE=,tag:Nbd246OWZ03f4gqTbHGugw==,type:str]
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: pgadmin
type: Opaque
sops:
    age:
        - recipient: age16yfug5lv775x0678ulnx823uu6nh2qvnq8kfuy65tg8k2n6ulvjsqt6js7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL1Vvei9rb21zaEZxYy9y
            ZWhvUFFYKzIrQ1F3VmdxZHNSellqK2Vmc2hZCndRTytoOVNsVm0vdCt2TGNjUXJr
            ZS9Qclc2Vy8zVVYzRFVvNWtpb0ppUk0KLS0tIExvaEczVUVoaCtIQzkrdTBOZkJG
            TzdRdkFPUEJGWW0xazhEdHoweTdNbUUKnpCjWC20iTYOIq684WlUdApGGBvvBlt8
            fETHcv+QvtDRlw30GBp3TBGWYCrw2Od3ytrOTGNrgLp22WyA7KDthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T16:11:40Z"
    mac: ENC[AES256_GCM,data:MSc8gmjMZGmK6VM+AhpQ3Ss0q1zwuNKg9XBXY7WlR+orwII9SCVXoqzOu1nnJjcPhPnZqh8B51w/ngVAsF94GyIFu+B/4V+MyCYUe209hVM3JZ3oEjgFC5IfgJAz7jAcFouTHTfVsIN/pS14VEF3tmIbOsmtXLLG18P4Fzj8iDs=,iv:52VewdyvfqzO1YAssUF749u6NAxdGSzImPGWs9RF3cA=,tag:kqpVDm3reF6WhYwxw1/O/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
