apiVersion: ENC[AES256_GCM,data:+3Y=,iv:a55WtdYFxO4nfwXIXVClY/Hdlm6R7ZHOkWj/9x6j7Kw=,tag:mPQ2yHAt4tzXY2Y1pQLIPg==,type:str]
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:YKQyMwAhWjhX2J1X5DRBqa1H/nVFDQqilR9xwNkIE9QUKpPh,iv:IapgxNO1UJtpybeI+C4rYWhwhKW4nG768XGziRRncCk=,tag:8iGD+wu8AfTllsPhYm+bKA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:f9efOhseMDQ=,iv:lYW+LKowxQBmMNOpu1pvn8ylsc1fcZDoN/oMyko3YGc=,tag:CnWwJF5WUtArYwwf/To5Gg==,type:str]
kind: ENC[AES256_GCM,data:f8mL3FFU,iv:M407zSl6IFm3XmKiyGupBat/sBbWSWuH6n+Im0WVIjM=,tag:+laNVwviYL8b+q0h0yw3tA==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:TJv+2pr1wphPMoVY1JXyblkpABU=,iv:utwctIXtOqg0Qc2I3FhTvWdDc3gWqZJlUma++nA8ZN4=,tag:4JqypYSFmQ1JJgkO8NWeAw==,type:str]
    name: ENC[AES256_GCM,data:rs9EsSwSnITRec7Odzk=,iv:qDQq7ZMs2A/s/Htq3USabrPBkbu2nt6izZQ0g6cORg0=,tag:/v3N3KP1F5kyaZ0TLsNSnw==,type:str]
    namespace: ENC[AES256_GCM,data:Vew22i4YPw==,iv:WC34vMAe5o/2gmwEQvecrRuCY3ywDy7pIFrjfBP49Ws=,tag:kSVd38Hj7GXBPkJqvy6P/A==,type:str]
    resourceVersion: ENC[AES256_GCM,data:PyuIyaU+eds=,iv:Iq7OHLiehE3QSpcTgVnPOPb1WezcrUfQivC2wfHLmO0=,tag:gMI/JahyLO5bga5J6tnt6Q==,type:str]
    uid: ENC[AES256_GCM,data:eVRzOWds+dFK3IhGu+cGmc7tNugL4o5pkdlgbz1OVTcN9nxG,iv:iWJN85/NA/YBUZtD4LtFo0BsmheQ7z7hTzVAJ0Le55w=,tag:Xwv8YH3gYlygawjAchqSCg==,type:str]
type: ENC[AES256_GCM,data:gcAb+7Ej,iv:2sZ19ktn7NYu2ooNjfrX73jd3PBQBXrtwWOayF3RlxI=,tag:2xzvSrDnz+xsavNRMkTUjw==,type:str]
sops:
    age:
        - recipient: age16yfug5lv775x0678ulnx823uu6nh2qvnq8kfuy65tg8k2n6ulvjsqt6js7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR01LZy96b0gvbzM3MGpF
            UUlSZmNTd2U4SU9tNU9qZWxya1hpOUgvRVZnCldaVmFENmpjcjdLditCUUNXVGhN
            TnZEdzBnWmROd1hPV002SnZsWlV4M28KLS0tIC9JWTVYYVFGR0tMRHpGUm5SQjdl
            WS9CbXJsSXRoTG5ETVc0RGRWblRtcFkKuUaGL1bAc6J4ZfnCnP2KLs1nFN7OYu/r
            MAXY92zxldA2FZxqDVBHwYGYIBy/G/6zvd9VT6lVXoiOaZCbJ+wTAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T02:32:38Z"
    mac: ENC[AES256_GCM,data:P6vUw+t6muHjv1XF1u/1lqJ0FJX8qIy0stMZDaah/4rsv/+p3vStPcbKDi5ax4UKU5WzMwXh71cVf+kUTPaTrED99DD9szw4zzNdCNM0aWu3ljiL6Yj0HJBOAz9KyGXoJ+krpqoS6hxc2ITdC530TEtbYPg9TTCcuyfCwrgrkfk=,iv:zM2jK+vPi9kV0asqI25xndyUXohh+0octT8DWFcAKXo=,tag:/45tsIwbwNCdlcd/6bBlfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
