apiVersion: ENC[AES256_GCM,data:Ww8=,iv:O+1YFPjSCCZk5GatVlvTOYo/E8mxG3bK3TcIpsiQfLw=,tag:SC0Y2nhgl8MN8aVNEWfteQ==,type:str]
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:3T0461s8FGILFdw1DMMbm1DDnJ/woPEoyfw/iZrSq8ImLbhM,iv:z3UUhmb1VzzVZP1Np0OXqd36ba9kvrSXibMZz46VDYQ=,tag:nZJEl7XHLUA1iBHozn3+lw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:g2WSbNs8p/U=,iv:zvweCpgh63ImT4U2+9hTyeAXUqGWMiThXLtkCgxMfXI=,tag:7oI/mlrt0XJgEuYk4roJfg==,type:str]
kind: ENC[AES256_GCM,data:WsZ7zkJq,iv:gNlD4unYfJb12W3KR0GmvoF4niBqYxbypcSvTQZOlc8=,tag:HAnt7bCXr39dfURBSFij/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W02WAVWEeZlPqcxnqBs=,iv:WEQScbuvEofr7VafXasFq3gO7DJxlpH9Mi0fgkmXlgM=,tag:jyxk4amrBQ+jwRnPcwVLEg==,type:str]
    namespace: ENC[AES256_GCM,data:Tkrgm1DXWA==,iv:9id8Ws3GLvXaZ625OLLXJma81VThiKonEFmZpCQ+//k=,tag:HOmBqcLpbbMbxZ6sakewRA==,type:str]
type: ENC[AES256_GCM,data:qoxehLfU,iv:s5V4bk+6M4eaBa9uGW4kmBFJOmlyx1iXc3C2WcVUjJw=,tag:ChZkX3E1fMVrSJE2G3YuKw==,type:str]
sops:
    age:
        - recipient: age16yfug5lv775x0678ulnx823uu6nh2qvnq8kfuy65tg8k2n6ulvjsqt6js7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSVVXblEyeEh0c3R4d0xM
            R015T256dGVsZUQrbzlHWC9nMWx5WTlpL21NCmdhaWgyT09NeklJeWRaV0ZoOFJH
            UzY5M2ppMHU3OFdJV2hyTGE5WEdsSEUKLS0tIFh5YnFyckI3aTBDTFo3bUU4ZGpH
            bmJESmJHZUpybXBFWERZY05rd3RjRmsKbv/rpBo3eWJL44uBbZSYR0tdzYKIz3Lv
            7AY+99hi9F9URGTqlWrWXPlDcvHzpacjdRcPMksMxD/95HGqZLV+Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T03:14:12Z"
    mac: ENC[AES256_GCM,data:CVbrHswLDpDdQgP+imee9qD9mPgEArWGZ2yTYqnO5s7IYWGXCemERLGmJDTviSfpe5ALpeyQwVEzhmpOsYoNgcFG3EcIkekea+eX1MF71FD7G/dAqsOGE+MSIgQItFjjiTQ9A7vOkjpTEN6yB4/cxkcjtrJTb5EIwW8wQYcU6KE=,iv:NCU9tRfwhxBWQksb8aUEhRsfQevQPQPig3p4l1xmNWU=,tag:ZHZ1N1t9rGI2nQBGP2AsmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
