apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: wallabag/wallabag
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: pdo_pgsql
            - name: SYMFONY__ENV__DATABASE_HOST
              value: postgres-cluster-rw.postgres.svc.cluster.local
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: wallabag
            - name: SYMFONY__ENV__DATABASE_USER
              value: wallabag_user
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallabag-db-secret
                  key: database-password
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: http://192.168.1.204
          volumeMounts:
            - name: images
              mountPath: /var/www/wallabag/web/assets/images
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: wallabag-images-pvc
