apiVersion: v1
kind: Service
metadata:
  name: wallabag
  namespace: wallabag
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.204
  selector:
    app: wallabag
  ports:
    - port: 80
      targetPort: 80
