apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true # default, enable ingress
    traefik: true # enable traefik ingressRoute
    gateway: true # enable gateway-api
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Homelab:
        - Mealie:
            href: http://mealie.kevin-morris.net
            icon: mealie.png
            description: Recipes

        - Grafana:
            href: http://grafana.kevin-morris.net
            icon: grafana.png
            description: Monitoring

        - Linkding:
            href: http://linkding.kevin-morris.net
            icon: linkding.png
            description: Bookmarks
        
        - Audiobookshelf:
            href: http://audiobooks.kevin-morris.net
            icon: audiobookshelf.png
            description: Audiobookshelf

    - Consuming:
        - Hacker News:
            href: https://news.ycombinator.com
            icon: hacker-news.png
            description: Hacker News

        - YouTube:
            href: https://www.youtube.com/
            icon: youtube.png
            description: YouTube

    - Creating:
        - LinkedIn:
            href: https://www.linkedin.com/feed/
            icon: linkedin.png
            description: LinkedIn

        - X:
            href: https://x.com/home
            icon: x.png
            description: X

    - Learning:
        - Kubernetes:
            href: http://kubernetes.io/docs/home
            icon: kubernetes.png
            description: Kubernetes

        - Skool:
            href: https://www.skool.com/kubecraft/classroom
            icon: google-scholar.png
            description: Skool

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Careus"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default

    - resources:
        label: System
        cpu: true
        memory: true

    - resources:
        label: Specs
        cputemp: true
        #tempmin: 0 # optional, minimum cpu temp
        #tempmax: 100 # optional, maximum cpu temp
        uptime: true
        units: imperial # only used by cpu temp, options: 'imperial' or 'metric'
        refresh: 3000 # optional, in ms

    - resources:
        network: true # optional, uses 'default' if true or specify a network interface name

    - resources:
        label: Storage
        disk: /mnt/p1
        diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

    - search:
        provider: duckduckgo
        target: _blank
    - openweathermap:
        label: Morrisville #optional
        latitude: 35.82348
        longitude: -78.82556
        units: imperial # or metric
        provider: openweathermap
        apiKey: e172ad44cf206c004ba7f8e04557d12d # required only if not using provider, this reveals api key in requests
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 0
    - greeting:
        text_size: xl
        text: Welcome to Homepage!
  docker.yaml: ""
