apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true # default, enable ingress
    traefik: true # enable traefik ingressRoute
    gateway: true # enable gateway-api
  settings.yaml: |
    title: Homepage*
    background: /images/homepage.jpg
    headerStyle: boxed
    theme: dark # or light
    color: zinc
    layout:
      Homelab:
        style: column
      Apps:
        style: column
      Creating:
        style: column
      Consuming:
        style: column
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
  services.yaml: |
    - Homelab:
        - Grafana:
            href: http://grafana.kevin-morris.net
            icon: grafana.png
            description: Monitoring

    - Apps:
        - Mealie:
            href: http://mealie.kevin-morris.net
            icon: mealie.png
            description: Recipes

        - Linkding:
            href: http://linkding.kevin-morris.net
            icon: linkding.png
            description: Bookmarks

        - Audiobookshelf:
            href: http://audiobooks.kevin-morris.net
            icon: audiobookshelf.png
            description: Audiobookshelf

        - Calibre:
            href: http://192.168.1.202:8083
            icon: calibre.png
            description: Calibre

    - Creating:
        - LinkedIn:
            href: https://www.linkedin.com/feed/
            icon: linkedin.png
            description: LinkedIn

        - X:
            href: https://x.com/home
            icon: x.png
            description: X

        - Blog:
            href: https://kevin-morris.net
            icon: kubernetes.png
            description: Blog

    - Consuming:
        - Hacker News:
            href: https://news.ycombinator.com
            icon: hacker-news.png
            description: Hacker News

        - YouTube:
            href: https://www.youtube.com/
            icon: youtube.png
            description: YouTube

        - Commafeed:
            href: http://commafeed.kevin-morris.net
            icon: commafeed.png
            description: Commafeed

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Careus"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        disk: /
        cputemp: true
        network: default
        tempmin: 0 # optional, minimum cpu temp
        tempmax: 100 # optional, maximum cpu temp
        uptime: true
        units: metric # only used by cpu temp, options: 'imperial' or 'metric'
        refresh: 3000 # optional, in ms
        diskUnits: bytes
    - openmeteo:
        label: Morrisville # optional
        latitude: 35.8235
        longitude: -78.8256
        timezone: Europe/Kiev # optional
        units: metric # or imperial
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 1
    - search:
        provider: brave
        target: _blank
  docker.yaml: ""
