apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true # default, enable ingress
    traefik: true # enable traefik ingressRoute
    gateway: true # enable gateway-api
  settings.yaml: |
    theme: dark # or light
    color: zinc
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Tools:

        - Github:
            - icon: github.png
              href: https://github.com/
        - Claude:
            - icon: claude-ai.png
              href: https://claudeai.new/

    - Learning:
        - Kubernetes:
            - href: http://kubernetes.io/docs/home
              icon: kubernetes.png

  services.yaml: |
    - Homelab:

        - Grafana:
            href: http://grafana.kevin-morris.net
            icon: grafana.png
            description: Monitoring
    - Apps:

        - Mealie:
            href: http://mealie.kevin-morris.net
            icon: mealie.png
            description: Recipes

        - Linkding:
            href: http://linkding.kevin-morris.net
            icon: linkding.png
            description: Bookmarks

    - Creating:

        - LinkedIn:
            href: https://www.linkedin.com/feed/
            icon: linkedin.png
            description: LinkedIn

        - X:
            href: https://x.com/home
            icon: x.png
            description: X


    - Consuming:
        - Hacker News:
            href: https://news.ycombinator.com
            icon: hacker-news.png
            description: Hacker News

        - YouTube:
            href: https://www.youtube.com/
            icon: youtube.png
            description: YouTube
        
        - Audiobookshelf:
            href: http://audiobooks.kevin-morris.net
            icon: audiobookshelf.png
            description: Audiobookshelf
        
        - Calibre:
            href: http://192.168.1.200:8080
            icon: calibre.png
            description: Calibre
  
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Careus"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        cputemp: true
        network: default
        #tempmin: 0 # optional, minimum cpu temp
        #tempmax: 100 # optional, maximum cpu temp
        uptime: true
        units: metric # only used by cpu temp, options: 'imperial' or 'metric'
        refresh: 3000 # optional, in ms
    - search:
        provider: brave
        target: _blank
  docker.yaml: ""
