apiVersion: v1
data:
    SMTP_PASSWORD: ENC[AES256_GCM,data:c494eGXcJhvqU6rIsg7gzoPKvWGn0A9weRVkXQ==,iv:QVz7/+4/HQj9oG3q/laayA59qGLYYfTURHCsyT1ewTk=,tag:Xmm6/T7XdJMnra44d6jsbg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:/di4cpww/itu2WOsHK+q+RNWrgMXxPZSUpRp2k7KIy1FxLeG,iv:zC9yw11z7fkr2JHaR80dLLbJIHeyqZH56CsDJg+u1JM=,tag:A3+GqILkF8I7YKBiS4Ocsw==,type:str]
kind: Secret
metadata:
    name: mealie-container-env
sops:
    age:
        - recipient: age16yfug5lv775x0678ulnx823uu6nh2qvnq8kfuy65tg8k2n6ulvjsqt6js7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNG5kbUE5Nkw2UDBaNUFr
            V0F0OUlXTU9sS3NQL3lCZldiZTJLZUQrM1hrCmZnd09ZNHR4ZGJQdW1TdkxrNFJm
            ZURzWFhHZ0lCZndSM3Y2OGhwaUU4eGcKLS0tIFhUL2xBVmhlRHRYblgyYWgvZGlz
            dW9BL1hFbi9xVTFjNDFaeGN4cVlXdUEK0AvhATx2/nHpajSdoAZcsB2JDpYReICD
            zV6S/rZdK5Toa/RfM+ckzq+yAS3nGPJbSOyiF1s4GX2dOwdn+KW78Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T23:45:41Z"
    mac: ENC[AES256_GCM,data:TpCB1meR88UgrEUGqZYC18ric3odhmsTndqQgOUHd6d/o6XO6JK5BJPmrGXhiBRvByC2JmH1WBt0J7G9nAeYTpcGbSVvC4ACSbSxrR2TqC2oU6rYzln+uf3vk6yNnCNVEtBhQTZLn+btxug2oMRbJpKknyS16cOYJu6bdGtV3Gw=,iv:Cv7s0av++dD1avDBQaC7CQIYMYraTRezDV+xco2NBpM=,tag:bERk6vsdjDsNVaIe3EQacQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
