apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: pgadmin
  annotations:
    metallb.io/loadBalancerIPs: 192.168.1.243
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
