apiVersion: ENC[AES256_GCM,data:Zq4=,iv:rTqQLPVUlGHPvBWivAsWKvX4PEk2J4l8liXOLP2vsOA=,tag:fqBMYHVi0D2weqj+Rat1Ng==,type:str]
kind: ENC[AES256_GCM,data:oNAGzGCi,iv:s0ZZstUb77msE6B+3IeVjSEpG1Nafew0Q3aHcKaVN6w=,tag:ueLnXo+Kvjzqes5CFDMu2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aKWRMqN1CfwEmtgHW/xbdgv07sw=,iv:hpGbxhpBZUJ/Da1tv4IyBw2DDXce9e+VWB00GiralIA=,tag:92wHRq5ckWcuY0C1gWoayA==,type:str]
    namespace: ENC[AES256_GCM,data:zFrs5T9IKJDmUA==,iv:NhRaiPnyNkwx9e3zv+qc1ytyQbDUvbfh2sWV5iGoVsQ=,tag:okO7gxcO+NVXqZvCwf1RLw==,type:str]
type: ENC[AES256_GCM,data:XSkaUqkC,iv:P0Y93SAXSGhNghjCKBSZhX7KX5lOS8PJ8AvJ/qb2m+E=,tag:4VTzpE8QEG6GfP51XCZp6g==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:y0+Bj8I=,iv:ulSLwdIE1mT//ckHL+XVpsLg+ynz47i9EjfJyKiCV44=,tag:/lT4z7Llxj0QVh67laKfjQ==,type:str]
    admin-password: ENC[AES256_GCM,data:LAZRhPwpMJzl,iv:VIFpdCINTM6qhY+yJRRKeQ0j4hNKWfmeovhMEITc7Cc=,tag:GlHQvRmKS4meuBGZOfhHkA==,type:str]
sops:
    age:
        - recipient: age16yfug5lv775x0678ulnx823uu6nh2qvnq8kfuy65tg8k2n6ulvjsqt6js7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd0pLUUtWYlVVZk5FcGV2
            aktPUlNHYjZQTU04Qko3T0xIaWVCSmJ5ZEFNCmZ6RWx3M2Nia3VHNXNoRDR2cFM1
            T0hnaGZwSktwRVlEUmEwTUJ6dXpqWHMKLS0tIHhSQzJEN0dmbUlwUnAyS1hDYkFk
            dXBPTEdyMmt4a3lqRGtsWnVKOFRodGcK6IPhdx5q2I9PM6LNVHChjPev1YauvlTO
            YORCcXMrKIvK9cvIjbS+22+IVkbxzG1bK7lMXUOHLQsmeHRpmhA3aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T02:54:52Z"
    mac: ENC[AES256_GCM,data:7qjiG16KK02YmW67cUwkAfZhidRJ9WiVKvm+UVzEl77yWQX323yeo/TqqgR5IX8dvZ7dEJGraasuO8rJhauFqugCq3JB+3EjW33dSWPvyEBrLWSrfmVxFNAxiV/HtJM07G7nlKzQ90cTb5cgYMJ3vbWMcV4bknA++q/la0+rCcs=,iv:t/OeMh6KFyoku82WOHHK4Ft+ZMdtzrfEOI3Wun+2fyc=,tag:1FjN4XQStsFG5OQlofEs7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
