apiVersion: ENC[AES256_GCM,data:Zq4=,iv:rTqQLPVUlGHPvBWivAsWKvX4PEk2J4l8liXOLP2vsOA=,tag:fqBMYHVi0D2weqj+Rat1Ng==,type:str]
kind: ENC[AES256_GCM,data:oNAGzGCi,iv:s0ZZstUb77msE6B+3IeVjSEpG1Nafew0Q3aHcKaVN6w=,tag:ueLnXo+Kvjzqes5CFDMu2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aKWRMqN1CfwEmtgHW/xbdgv07sw=,iv:hpGbxhpBZUJ/Da1tv4IyBw2DDXce9e+VWB00GiralIA=,tag:92wHRq5ckWcuY0C1gWoayA==,type:str]
    namespace: ENC[AES256_GCM,data:zFrs5T9IKJDmUA==,iv:NhRaiPnyNkwx9e3zv+qc1ytyQbDUvbfh2sWV5iGoVsQ=,tag:okO7gxcO+NVXqZvCwf1RLw==,type:str]
type: ENC[AES256_GCM,data:XSkaUqkC,iv:P0Y93SAXSGhNghjCKBSZhX7KX5lOS8PJ8AvJ/qb2m+E=,tag:4VTzpE8QEG6GfP51XCZp6g==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:LAZRhPwpMJzl,iv:VIFpdCINTM6qhY+yJRRKeQ0j4hNKWfmeovhMEITc7Cc=,tag:GlHQvRmKS4meuBGZOfhHkA==,type:str]
sops:
    age:
        - recipient: age16yfug5lv775x0678ulnx823uu6nh2qvnq8kfuy65tg8k2n6ulvjsqt6js7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd0pLUUtWYlVVZk5FcGV2
            aktPUlNHYjZQTU04Qko3T0xIaWVCSmJ5ZEFNCmZ6RWx3M2Nia3VHNXNoRDR2cFM1
            T0hnaGZwSktwRVlEUmEwTUJ6dXpqWHMKLS0tIHhSQzJEN0dmbUlwUnAyS1hDYkFk
            dXBPTEdyMmt4a3lqRGtsWnVKOFRodGcK6IPhdx5q2I9PM6LNVHChjPev1YauvlTO
            YORCcXMrKIvK9cvIjbS+22+IVkbxzG1bK7lMXUOHLQsmeHRpmhA3aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T02:10:24Z"
    mac: ENC[AES256_GCM,data:agiCHtZTvmPdI2L5F7v8F7H95HrJG0821GipNHoossrMoTOm38Pfu0e1yj7Q3Z+xQIDaGY9c2Wmhvv6/ddpHvj0iw+HqcKmQoE2RgEd4AawpSoWupavAV7x8M2CwqgBhhpQvQh0K0+jlq1reCpzLAswMGm6Qwjufvm+ph/ttpho=,iv:BLMs83cn+SovVNYK3rDYVlSyqi4hSDYLg96FbSej1pw=,tag:23wfepb5H1NbkwSdhZDfCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
